name: Build, Push, and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 473772085811.dkr.ecr.us-east-1.amazonaws.com

      # Step 4: Build, tag, and push Docker image
      - name: Build, tag, and push image to Amazon ECR
        run: |
          IMAGE_TAG=latest
          ECR_REPO=473772085811.dkr.ecr.us-east-1.amazonaws.com/mediplus
          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker push $ECR_REPO:$IMAGE_TAG

      # Step 5: Deploy to EC2 via SSH
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ECR_REPO=473772085811.dkr.ecr.us-east-1.amazonaws.com/mediplus
            docker stop mediplus || true
            docker rm mediplus || true
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 473772085811.dkr.ecr.us-east-1.amazonaws.com
            docker pull $ECR_REPO:latest
            docker run -d -p 80:8000 --name mediplus $ECR_REPO:latest


