name: Build, Push, and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin 473772085811.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Step 4: Build, tag, and push Docker image
      - name: Build, tag, and push Docker image
        run: |
          IMAGE_NAME=mediplus
          IMAGE_TAG=v1
          ECR_REPO=473772085811.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME

          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
          docker push $ECR_REPO:$IMAGE_TAG

      # Step 5: Deploy to EC2 via SSH
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_NAME=mediplus
            IMAGE_TAG=v1
            REGION=${{ secrets.AWS_REGION }}
            ECR_REPO=473772085811.dkr.ecr.$REGION.amazonaws.com/$IMAGE_NAME

            echo "Logging in to ECR..."
            aws ecr get-login-password --region $REGION \
            | docker login --username AWS --password-stdin 473772085811.dkr.ecr.$REGION.amazonaws.com

            echo "Stopping old container (if any)..."
            sudo docker stop $IMAGE_NAME || true
            sudo docker rm $IMAGE_NAME || true

            echo "Pulling new image..."
            sudo docker pull $ECR_REPO:$IMAGE_TAG

            echo "Starting container..."
            sudo docker run -d -p 80:80 --name $IMAGE_NAME $ECR_REPO:$IMAGE_TAG

            echo "Deployment successful!"




